- name: "Create user {{ linux_common_human_user | mandatory(msg='You must specify a username for the human user!') }}"
  ansible.builtin.user:
    name: "{{ linux_common_human_user }}"
    password: "{{ linux_common_human_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    # Enable append to not wipe out other group memberships
    append: true
    groups: "{{ linux_common_human_user_extra_groups }}"
  become: true
  tags: ["users"]

- name: Add known SSH key
  ansible.posix.authorized_key:
    user: "{{ linux_common_human_user }}"
    key: "{{ linux_common_human_ssh_public_key }}"
  tags: ["users"]

- name: Disable SSH password authentication
  ansible.builtin.copy:
    content: PasswordAuthentication no
    dest: /etc/ssh/sshd_config.d/DisablePasswordAuth.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload ssh
  become: true
  tags: ["configure"]

- name: Install helpful programs
  ansible.builtin.package:
    name:
      - nano
      - htop
      - ncdu
    state: present
  become: true
  tags: ["configure"]
