- name: Copy Prometheus config
  ansible.builtin.copy:
    src: prometheus.yml
    dest: "{{ monitoring_stack_prometheus_config_directory }}/prometheus.yml"
    owner: "{{ monitoring_stack_user }}"
    group: "{{ monitoring_stack_user }}"
    mode: "0600"
  become: true
