- name: Execute setup tasks
  ansible.builtin.include_tasks:
    file: setup.yml

- name: Prepare config files
  ansible.builtin.include_tasks:
    file: config.yml
  tags:
    - configure
    - configure-prometheus
    - configure-containers

- name: Run Docker Compose
  ansible.builtin.include_tasks:
    file: compose-stack.yml
  tags:
    - configure-containers
    - docker-compose

- name: Set up Grafana users
  ansible.builtin.include_tasks:
    file: users.yml
  tags:
    - users
    - configure-grafana

- name: Set up Prometheus data source in Grafana
  ansible.builtin.include_tasks:
    file: datasources.yml
  tags:
    - configure
    - configure-prometheus

- name: Import dashboards from grafana.com
  ansible.builtin.include_tasks:
    file: dashboards/import_from_grafana_website.yml
  when: monitoring_stack_grafana_dashboards_import_ids | length > 0
  tags:
    - dashboards
    - configure-grafana

- name: Import dashboards from role
  ansible.builtin.include_tasks:
    file: dashboards/import_from_role.yml
  tags:
    - dashboards
    - configure-grafana
  # TODO: make this run based off whether there are files in the `files/` directory,
  #       if the loop inside the role doesn't already handle that for us
