# Ansible connection configurations. Shouldn't need to change much!
ansible_user: ansible_provision
ansible_ssh_private_key_file: ssh/ansible_provision.pem
ansible_become_method: sudo
ansible_become_password: "{{ secrets_ansible_password }}"

# Human identities. Drop in your public key!
human_user: offworld-admin
human_password: "{{ secrets_human_password }}"
human_ssh_public_key: ""
human_user_extra_groups:
  - "sudo"

# Map our vars for the linux_common role
linux_common_human_user: "{{ human_user }}"
linux_common_human_password: "{{ human_password }}"
linux_common_human_ssh_public_key: "{{ human_ssh_public_key }}"
linux_common_human_user_extra_groups: "{{ human_user_extra_groups }}"
