- name: Provision monitoring server
  hosts: monitoring_servers
  gather_facts: true
  roles:
    - role: linux_common
      tags:
        - linux_common

    - role: geerlingguy.docker
      become: true
      tags:
        - docker

    - role: prometheus.prometheus.node_exporter
      tags:
        - node_exporter
        - prometheus

    - role: monitoring_stack
      tags:
        - monitoring_stack
        - prometheus
        - grafana
