- name: Provision monitoring server
  hosts: monitoring_servers
  gather_facts: true
  roles:
    - role: linux_common
      tags:
        - linux_common
      vars:
        linux_common_human_user: "{{ human_user }}"
        linux_common_human_password: "{{ human_password }}"
        linux_common_human_ssh_public_key: "{{ human_ssh_public_key }}"
        linux_common_human_user_extra_groups: "{{ human_user_extra_groups }}"

    - role: docker
      tags:
        - docker
      vars:
        # See the geerlingguy.docker Readme for all the available configuration options!
        docker_edition: ce
        docker_users:
          - "{{ human_user }}"
        # Expose the Daemon's stats on a port for Prometheus to consume
        docker_daemon_options:
          metrics-addr: "{{ ansible_facts.default_ipv4.address }}:9323"

    - role: prometheus.prometheus.node_exporter
      tags:
        - node_exporter
        - prometheus
      vars:
        # Intentionally empty this var so node_exporter doesn't require authentication
        # TODO: assess whether this is a security problem when metrics are only accessible locally
        node_exporter_basic_auth_users: {}
        # Using the machine's LAN IPv4 address, as the loopback and localhost addresses weren't accessible
        # inside the Docker network. Better than 0.0.0.0, but it'd be nice to tighten up further in the future.
        node_exporter_web_listen_address: "{{ ansible_facts.default_ipv4.address }}:9100"

    - role: monitoring_stack
      tags:
        - monitoring_stack
        - prometheus
        - grafana
      vars:
        # Action that docker compose should take. Change this if you want to
        # force the docker compose stack to do something other than just create/update itself.
        # Must be one of: [absent, stopped, restarted, present]
        monitoring_stack_docker_compose_state: present
        monitoring_stack_grafana_default_admin_password: "{{ grafana_default_admin_password }}"
        monitoring_stack_grafana_users: "{{ grafana_users }}"
        # See roles/monitoring_stack/README.md
        monitoring_stack_grafana_dashboards_import_ids:
          # Imports this dashboard: https://grafana.com/grafana/dashboards/1860-node-exporter-full/
          - id: 1860
            revision: 37
            folder: "Node"
