- name: Provision monitoring server
  hosts: monitoring_servers
  gather_facts: true
  roles:
    - role: linux_common
      vars:
        linux_common_human_user: "{{ human_user }}"
        linux_common_human_password: "{{ human_password }}"
        linux_common_human_ssh_public_key: "{{ human_ssh_public_key }}"
        linux_common_human_user_extra_groups: "{{ human_user_extra_groups }}"
    - role: docker
      tags:
        - docker
      vars:
        docker_edition: ce
        # Set to false to use the version of Docker pinned for 24.04 LTS
        docker_add_repo: true
        docker_users:
          - "{{ human_user }}"
        # Expose the Daemon's stats on a port for Prometheus to consume
        docker_daemon_options:
          metrics-addr: "0.0.0.0:9323"
    - role: prometheus.prometheus.node_exporter
      tags:
        - node_exporter
        - prometheus
      vars:
        # Intentionally empty this var so node_exporter doesn't require authentication
        # TODO: assess whether this is a security problem when metrics are only accessible locally
        node_exporter_basic_auth_users: {}
        # Bind to the loopback address so we don't expose the node_exporter to the network
        # Or at least that was the plan! Need to figure out a way to allow traffic from the
        # Docker network, or else these ports will need to be firewalled instead
        node_exporter_web_listen_address: "0.0.0.0:9100"
    - role: monitoring_stack
      tags:
        - monitoring_stack
        - prometheus
        - grafana
